# Generated by Django 3.0.4 on 2020-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_stream_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
