# Generated by Django 3.0.4 on 2020-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_stream_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
