# Generated by Django 3.0.4 on 2020-03-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artworktag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworktag',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.ArtWork'),
        ),
    ]
