# Generated by Django 3.0.4 on 2020-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20200317_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
